// ============================================================
//  PVF 社区标签注释数据（PVF_TAGS 条目格式，标签定义合并表的社区基座）
//  来源：外部知识包内置社区标签注释（344 条，CC0-1.0 公共领域许可，
//  可自由复用、无需署名）；提取规则与集成方式见 docs/pvf-tag-community-comments.md。
//  条目格式与 PVF_TAGS 一致：category 固定 "community"、description 取去重后首条注释、
//  remark 为其余注释以「；」连接（无则省略）、fileTypes 为社区库原始数值
//  数组（与原始注释条数等长，含义未确证，仅存档不展示）。
//  条目单行紧凑展示（prettier-ignore 豁免格式化）。
//  合并与解析见 pvfTags.js（PVF_TAG_ENTRIES，人工定义优先覆盖本表）。
//  更新方式：重跑提取流程替换本文件后，运行 test/tag-comment-verify.mjs。
// ============================================================

// prettier-ignore
export const PVF_TAG_COMMENTS = {
    "dungeon start area": { category: "community", description: "进入该副本地图时的入场坐标（大概是）", fileTypes: [10] },
    "attack box": { category: "community", description: "攻击范围判定框", fileTypes: [1] },
    "image pos": { category: "community", description: "动画贴图坐标", fileTypes: [1] },
    "grade": { category: "community", description: "装备实际等级", fileTypes: [0] },
    "on die": { category: "community", description: "生命值耗尽", fileTypes: [21] },
    "on damage": { category: "community", description: "受到攻击", fileTypes: [21] },
    "on attack": { category: "community", description: "发起攻击", fileTypes: [21] },
    "on etc": { category: "community", description: "特殊触发", fileTypes: [11] },
    "on appear": { category: "community", description: "游走", remark: "出现在自身附近时", fileTypes: [11,11] },
    "sight": { category: "community", description: "视力", fileTypes: [11] },
    "physical attack bonus": { category: "community", description: "物理攻击力", fileTypes: [3] },
    "magical attack bonus": { category: "community", description: "魔法攻击力", fileTypes: [3] },
    "weight": { category: "community", description: "若为装备或物品时，将减少物品栏或金库的容量", fileTypes: [3] },
    "on revenge": { category: "community", description: "产生仇恨目标时", fileTypes: [11] },
    "keep distance with target": { category: "community", description: "与敌对目标保持的攻击距离", fileTypes: [21] },
    "vision": { category: "community", description: "视力", fileTypes: [21] },
    "magical": { category: "community", description: "魔法伤害", fileTypes: [15] },
    "physical": { category: "community", description: "物理伤害", fileTypes: [15] },
    "(down)": { category: "community", description: "下", fileTypes: [15] },
    "(skill)": { category: "community", description: "Z（可以单独作为一个手搓指令）", fileTypes: [15] },
    "(attack)": { category: "community", description: "普攻", fileTypes: [15] },
    "command key explain": { category: "community", description: "手搓指令的释放介绍", fileTypes: [15] },
    "(buff)": { category: "community", description: "空格键（可以单独作为一个手搓指令）", fileTypes: [15] },
    "(right)": { category: "community", description: "右（同时也对应手搓指令的向前移动）", fileTypes: [15] },
    "(left)": { category: "community", description: "左（同时也对应手搓指令的向后移动）", fileTypes: [15] },
    "(up)": { category: "community", description: "上", fileTypes: [15] },
    "durability decrease rate": { category: "community", description: "使用技能所消耗的耐久", fileTypes: [15] },
    "casting time": { category: "community", description: "施法时间", fileTypes: [15] },
    "shake screen": { category: "community", description: "释放技能在部分时候的屏幕抖动效果", fileTypes: [15] },
    "on village": { category: "community", description: "处于【怪物攻城战】期间时", fileTypes: [11] },
    "on stand": { category: "community", description: "处于站立状态时", fileTypes: [21] },
    "on disappear": { category: "community", description: "[on appear]台词结束后接上的话", fileTypes: [21] },
    "attack damage rate": { category: "community", description: "伤害比例", fileTypes: [21] },
    "quick item": { category: "community", description: "快捷栏道具", fileTypes: [21] },
    "rigidity": { category: "community", description: "硬直", fileTypes: [3] },
    "stun": { category: "community", description: "异常效果", fileTypes: [0] },
    "coin limit": { category: "community", description: "副本内的复活次数", fileTypes: [6] },
    "experience increasing point": { category: "community", description: "副本内的经验值获取倍率", fileTypes: [6] },
    "minimum required level": { category: "community", description: "开启地下城的等级", fileTypes: [6] },
    "basis level": { category: "community", description: "副本内怪物的平均等级", fileTypes: [6] },
    "fighter": { category: "community", description: "女格斗", fileTypes: [46] },
    "gunner": { category: "community", description: "男枪手", fileTypes: [46] },
    "mage": { category: "community", description: "女魔法", fileTypes: [46] },
    "priest": { category: "community", description: "男圣职", fileTypes: [46] },
    "gold multiple": { category: "community", description: "任务金币奖励倍数", fileTypes: [14] },
    "rarity": { category: "community", description: "稀有度", fileTypes: [0] },
    "weapon effect type": { category: "community", description: "伤害类型", fileTypes: [15] },
    "attack delay": { category: "community", description: "攻击延迟", fileTypes: [11] },
    "mp_regenrate": { category: "community", description: "每分钟恢复魔法值", fileTypes: [0] },
    "hp_regenrate": { category: "community", description: "每分钟恢复生命值", fileTypes: [0] },
    "attack_speed": { category: "community", description: "攻击速度", fileTypes: [0] },
    "demonic swordman": { category: "community", description: "黑暗武士", fileTypes: [0] },
    "skill levelup": { category: "community", description: "装备时提升的技能和等级限制", fileTypes: [0] },
    "hp max": { category: "community", description: "HP 最大值", fileTypes: [0] },
    "mp max": { category: "community", description: "MP 最大值", fileTypes: [0] },
    "url hyperlink": { category: "community", description: "URL超级链接", fileTypes: [32] },
    "required level": { category: "community", description: "学习等级", fileTypes: [15] },
    "physical magical change": { category: "community", description: "物理、魔法伤害转换", fileTypes: [15] },
    "party": { category: "community", description: "对身边友军也会生效", fileTypes: [3] },
    "poison": { category: "community", description: "异常效果", fileTypes: [3] },
    "freeze": { category: "community", description: "异常效果", fileTypes: [3] },
    "stone": { category: "community", description: "异常效果", fileTypes: [3] },
    "blind": { category: "community", description: "异常效果", fileTypes: [3] },
    "confuse": { category: "community", description: "异常效果", fileTypes: [3] },
    "bleeding": { category: "community", description: "异常效果", fileTypes: [3] },
    "sleep": { category: "community", description: "异常效果", fileTypes: [3] },
    "disease": { category: "community", description: "异常效果", fileTypes: [3] },
    "silence": { category: "community", description: "异常效果", fileTypes: [3] },
    "consume mp": { category: "community", description: "MP 消耗", fileTypes: [15] },
    "league ban": { category: "community", description: "添加此代码可以在PVP对局中禁用此技能", fileTypes: [15] },
    "consume item": { category: "community", description: "第一个是释放技能要消耗的物品代码", fileTypes: [15] },
    "skill fitness second growtype": { category: "community", description: "这个标签可为此技能添加觉醒限制", fileTypes: [15] },
    "coin": { category: "community", description: "复活币", fileTypes: [26] },
    "premium": { category: "community", description: "时效道具", fileTypes: [26] },
    "creature": { category: "community", description: "宠物", fileTypes: [26] },
    "package": { category: "community", description: "礼包", fileTypes: [26] },
    "avatar": { category: "community", description: "时装店出售的商品列表", fileTypes: [26] },
    "seria blessing": { category: "community", description: "赛丽亚的祝福活动", fileTypes: [32] },
    "any": { category: "community", description: "所有异常状态效果", fileTypes: [3] },
    "minimum level": { category: "community", description: "使用所需的最低等级", fileTypes: [3] },
    "attach type": { category: "community", description: "绑定类型", fileTypes: [3] },
    "my status": { category: "community", description: "使自己进入状态异常", fileTypes: [3] },
    "stat change duration": { category: "community", description: "道具效果持续时间", fileTypes: [3] },
    "magical defense bonus": { category: "community", description: "魔法防御力", fileTypes: [3] },
    "physical defense bonus": { category: "community", description: "物理防御力", fileTypes: [3] },
    "physical critical hit": { category: "community", description: "物理暴击率", fileTypes: [3] },
    "magical critical hit": { category: "community", description: "魔法暴击率", fileTypes: [3] },
    "lightning": { category: "community", description: "异常效果", fileTypes: [9] },
    "no element": { category: "community", description: "无元素属性", fileTypes: [9] },
    "amulet": { category: "community", description: "装备", fileTypes: [3] },
    "wrist": { category: "community", description: "装备", fileTypes: [3] },
    "ring": { category: "community", description: "装备", fileTypes: [3] },
    "fire attack": { category: "community", description: "火属性强化", fileTypes: [3] },
    "title name": { category: "community", description: "装备", fileTypes: [3] },
    "weapon": { category: "community", description: "装备", fileTypes: [3] },
    "coat": { category: "community", description: "装备", fileTypes: [3] },
    "string data": { category: "community", description: "用于硬编码的字符串数据", fileTypes: [3] },
    "pants": { category: "community", description: "装备", fileTypes: [3] },
    "shoulder": { category: "community", description: "装备", fileTypes: [3] },
    "waist": { category: "community", description: "装备", fileTypes: [3] },
    "shoes": { category: "community", description: "装备", fileTypes: [3] },
    "magic stone": { category: "community", description: "装备", fileTypes: [3] },
    "support": { category: "community", description: "装备", fileTypes: [3] },
    "slow": { category: "community", description: "异常效果", fileTypes: [9] },
    "hybrid": { category: "community", description: "组合体", fileTypes: [11] },
    "range combat": { category: "community", description: "远程攻击", fileTypes: [11] },
    "machine": { category: "community", description: "机械", fileTypes: [11] },
    "close-tough": { category: "community", description: "贴身", fileTypes: [11] },
    "spirit": { category: "community", description: "精灵族", fileTypes: [11] },
    "fixture": { category: "community", description: "固定位置", fileTypes: [11] },
    "dragon": { category: "community", description: "龙族", fileTypes: [11] },
    "tau": { category: "community", description: "牛头族", fileTypes: [11] },
    "close-manace": { category: "community", description: "施压", fileTypes: [11] },
    "goblin": { category: "community", description: "哥布林族", fileTypes: [11] },
    "human": { category: "community", description: "人形", fileTypes: [11] },
    "beast": { category: "community", description: "野兽", fileTypes: [11] },
    "fort armor": { category: "community", description: "建筑护甲", fileTypes: [11] },
    "close-passive": { category: "community", description: "被动攻击", fileTypes: [11] },
    "undead": { category: "community", description: "不死族", fileTypes: [11] },
    "lugaru": { category: "community", description: "猫妖族", fileTypes: [11] },
    "plant": { category: "community", description: "植物", fileTypes: [11] },
    "insect": { category: "community", description: "昆虫", fileTypes: [11] },
    "cut": { category: "community", description: "打击类型", fileTypes: [9] },
    "blow": { category: "community", description: "打击类型", fileTypes: [9] },
    "magic": { category: "community", description: "魔法", fileTypes: [9] },
    "physic": { category: "community", description: "物理", fileTypes: [9] },
    "ignore defense": { category: "community", description: "无视防御的伤害", fileTypes: [9] },
    "attack type": { category: "community", description: "伤害类型（隔一行再编辑）", fileTypes: [9] },
    "attackinfo": { category: "community", description: "攻击数据信息", fileTypes: [15] },
    "lift up": { category: "community", description: "浮空值", fileTypes: [9] },
    "hit direction": { category: "community", description: "判定方向", fileTypes: [9] },
    "back": { category: "community", description: "判定方向", fileTypes: [9] },
    "front": { category: "community", description: "判定方向", fileTypes: [9] },
    "pvp": { category: "community", description: "决斗场中的效果", fileTypes: [15] },
    "cool time": { category: "community", description: "冷却时间", fileTypes: [15] },
    "damage box": { category: "community", description: "受击判定框", fileTypes: [1] },
    "damage bonus": { category: "community", description: "伤害比率", fileTypes: [9] },
    "frame max": { category: "community", description: "整个动画过程播放的最大帧数", fileTypes: [1] },
    "skill under cooltime effect each": { category: "community", description: "冷却时间中的技能", fileTypes: [15] },
    "elementalmaster": { category: "community", description: "元素师", fileTypes: [28] },
    "none": { category: "community", description: "该词条位于技能树时", fileTypes: [28] },
    "summoner": { category: "community", description: "召唤师", fileTypes: [28] },
    "battlemage": { category: "community", description: "战斗法师", fileTypes: [28] },
    "witch": { category: "community", description: "魔道学者", fileTypes: [28] },
    "nenmaster": { category: "community", description: "气功师", fileTypes: [28] },
    "striker": { category: "community", description: "散打", fileTypes: [28] },
    "streetfighter": { category: "community", description: "街霸", fileTypes: [28] },
    "grappler": { category: "community", description: "柔道家", fileTypes: [28] },
    "crusader": { category: "community", description: "圣骑士", fileTypes: [28] },
    "infighter": { category: "community", description: "蓝拳圣使", fileTypes: [28] },
    "rogue": { category: "community", description: "暗夜使者转职", fileTypes: [28] },
    "necromancer": { category: "community", description: "暗夜使者转职", fileTypes: [28] },
    "avenger": { category: "community", description: "圣骑士转职", fileTypes: [28] },
    "exorcist": { category: "community", description: "圣骑士转职", fileTypes: [28] },
    "maximum level": { category: "community", description: "最高等级", fileTypes: [15] },
    "skill under cooltime effect": { category: "community", description: "施放过后会一同进入冷却时间的技能", fileTypes: [15] },
    "next skill": { category: "community", description: "关联技能", fileTypes: [28] },
    "purchase cost": { category: "community", description: "学得此技能所需的sp点", fileTypes: [15] },
    "reward selection int data": { category: "community", description: "完成任务时", fileTypes: [14] },
    "reward int data": { category: "community", description: "完成任务时给予的固定奖励", fileTypes: [14] },
    "special purchase cost": { category: "community", description: "学得此技能所需的tp点", fileTypes: [15] },
    "required level range": { category: "community", description: "等级间隔", fileTypes: [15] },
    "loop": { category: "community", description: "循环", fileTypes: [1] },
    "frame000": { category: "community", description: "这是每个动画的第一帧，", fileTypes: [1] },
    "buff": { category: "community", description: "使自己进入状态异常（基本以外的那些）", fileTypes: [3] },
    "warlike": { category: "community", description: "攻击欲望", fileTypes: [21] },
    "additional character status": { category: "community", description: "APC的面板", fileTypes: [21] },
    "character status rate": { category: "community", description: "APC的面板倍率", fileTypes: [21] },
    "quick skill": { category: "community", description: "快捷栏技能", fileTypes: [21] },
    "ai pattern": { category: "community", description: "AI逻辑", fileTypes: [21,8] },
    "name": { category: "community", description: "在游戏中所显示的第1个名字", fileTypes: [15] },
    "stun resistance": { category: "community", description: "眩晕抗性", fileTypes: [11] },
    "down": { category: "community", description: "动作值判定", fileTypes: [9] },
    "icon": { category: "community", description: "图标图像文件和帧索引", fileTypes: [3] },
    "superarmor": { category: "community", description: "霸体", fileTypes: [1] },
    "animation job": { category: "community", description: "使用该动画的职业", fileTypes: [0] },
    "move wav": { category: "community", description: "掉落、移动、使用音效", fileTypes: [0] },
    "common": { category: "community", description: "该词条位于导师技能商店内时", fileTypes: [24] },
    "swordman": { category: "community", description: "男鬼剑士", fileTypes: [24] },
    "use zoom rate": { category: "community", description: "副本内镜头缩放倍率", fileTypes: [6] },
    "champion": { category: "community", description: "出现精英怪的几率", fileTypes: [6] },
    "use effect explain": { category: "community", description: "道具自带的使用效果介绍开关", fileTypes: [3] },
    "pre required skill": { category: "community", description: "学得所需的前置技能", fileTypes: [15] },
    "start cool time": { category: "community", description: "开始冷却", fileTypes: [15] },
    "exposed by npc": { category: "community", description: "是否显示在NPC的任务界面", fileTypes: [14] },
    "at mage": { category: "community", description: "男魔法师", fileTypes: [24] },
    "level info": { category: "community", description: "级别信息/动态数据", fileTypes: [15] },
    "level property": { category: "community", description: "游戏内的技能属性", fileTypes: [15] },
    "static data": { category: "community", description: "静态数据", fileTypes: [15] },
    "command": { category: "community", description: "技能指令", fileTypes: [15] },
    "at fighter": { category: "community", description: "男格斗", fileTypes: [24] },
    "second growtype maximum level": { category: "community", description: "觉醒之后可学得的最高等级", fileTypes: [15] },
    "type": { category: "community", description: "类型", fileTypes: [14] },
    "int data": { category: "community", description: "int数据", fileTypes: [14] },
    "sub type": { category: "community", description: "子项目类型", fileTypes: [14] },
    "poison resistance": { category: "community", description: "中毒抗性", fileTypes: [0] },
    "bleeding resistance": { category: "community", description: "出血抗性", fileTypes: [0] },
    "if": { category: "community", description: "作为特效或效果的某种触发条件使用", fileTypes: [0] },
    "then": { category: "community", description: "[then]作为触发效果", fileTypes: [0] },
    "equipment physical defense": { category: "community", description: "物理防御力(地下城) 物理防御力(决斗场)", fileTypes: [0] },
    "equipment_physical_defense": { category: "community", description: "装备物理防御", fileTypes: [11] },
    "equipment_magical_defense": { category: "community", description: "装备魔法防御", fileTypes: [11] },
    "equipment_physical_attack": { category: "community", description: "装备物理攻击", fileTypes: [11] },
    "equipment_magical_attack": { category: "community", description: "装备魔法攻击", fileTypes: [11] },
    "equipment magical defense": { category: "community", description: "魔法防御力(地下城) 魔法防御力(决斗场)", fileTypes: [0] },
    "price": { category: "community", description: "价格", fileTypes: [3] },
    "value": { category: "community", description: "玩家卖给商店的金额", fileTypes: [0] },
    "need material": { category: "community", description: "所需材料道具索引", fileTypes: [0] },
    "difficulty": { category: "community", description: "difficulty 奖励权重 (百分比)", fileTypes: [26] },
    "gold limit from level": { category: "community", description: "每个等级可容纳的金币上限", fileTypes: [26] },
    "creator mage": { category: "community", description: "外传职业", fileTypes: [46] },
    "growtype maximum level": { category: "community", description: "每个职业可通过sp点或tp点学得此技能的最高等级", fileTypes: [15] },
    "skill fitness growtype": { category: "community", description: "为职业赋予这个技能", fileTypes: [15] },
    "character job": { category: "community", description: "职业", fileTypes: [28] },
    "job": { category: "community", description: "职业", fileTypes: [14] },
    "inventory_button": { category: "community", description: "背包按钮", fileTypes: [16] },
    "myinfo_button": { category: "community", description: "个人信息按钮", fileTypes: [16] },
    "quest_button": { category: "community", description: "任务按钮", fileTypes: [16] },
    "skill_button": { category: "community", description: "技能按钮", fileTypes: [16] },
    "auction_button": { category: "community", description: "拍卖行按钮", fileTypes: [16] },
    "cerashop_button": { category: "community", description: "商城按钮", fileTypes: [16] },
    "aura_gauge_lineardodge": { category: "community", description: "光环槽按钮（或许是）", fileTypes: [16] },
    "curse": { category: "community", description: "异常效果", fileTypes: [9] },
    "hold": { category: "community", description: "异常效果", fileTypes: [3] },
    "active status recovery": { category: "community", description: "解除异常效果", fileTypes: [3] },
    "equipment": { category: "community", description: "装备编号 品质 强化等级", fileTypes: [21] },
    "disjoint": { category: "community", description: "分解", fileTypes: [0] },
    "cast speed": { category: "community", description: "施放速度", fileTypes: [0] },
    "stat weights by rarity": { category: "community", description: "例如修改第一个数值0.4改1.4，相应的游戏里强化[普通]级装备的无视攻击也会提高", fileTypes: [26] },
    "apply ultimate": { category: "community", description: "若此标签在", fileTypes: [26] },
    "sp table": { category: "community", description: "左边是职业等级      右边是升到当前等级可获得的sp点", fileTypes: [26] },
    "close-carefully": { category: "community", description: "游击", fileTypes: [11] },
    "equipment physical attack": { category: "community", description: "物理攻击力(地下城) 物理攻击力(决斗场)", fileTypes: [0] },
    "equipment magical attack": { category: "community", description: "魔法攻击力(地下城) 魔法攻击力(决斗场)", fileTypes: [0] },
    "separate attack": { category: "community", description: "独立攻击力", fileTypes: [0] },
    "table": { category: "community", description: "强化/增幅属性（从左到右）", fileTypes: [26] },
    "index": { category: "community", description: "大概是编号", fileTypes: [2] },
    "level": { category: "community", description: "等级", remark: "在任务里代表接取任务角色的等级区间", fileTypes: [2,11] },
    "say speech": { category: "community", description: "处于此行动状态时的台词", fileTypes: [2] },
    "pos": { category: "community", description: "位置", fileTypes: [2] },
    "magic circle": { category: "community", description: "魔法阵", fileTypes: [2] },
    "summon monster": { category: "community", description: "召唤物机制", fileTypes: [2] },
    "weapon hit info": { category: "community", description: "武器命中信息", fileTypes: [46] },
    "increase status type": { category: "community", description: "使用此道具后获得的状态", fileTypes: [3] },
    "stuck": { category: "community", description: "命中率（正数减少", fileTypes: [9] },
    "hp regen rate": { category: "community", description: "每分钟恢复生命值", fileTypes: [11] },
    "item": { category: "community", description: "该标签位于怪物面板时", fileTypes: [11] },
    "world drop": { category: "community", description: "全局掉落", fileTypes: [26] },
    "push aside": { category: "community", description: "平推值", fileTypes: [9] },
    "breakable": { category: "community", description: "霸体", fileTypes: [11] },
    "with blast": { category: "community", description: "大概是狂龙之吼？", fileTypes: [11] },
    "damage type": { category: "community", description: "霸体代码", fileTypes: [1] },
    "delay": { category: "community", description: "一帧贴图的持续时间", fileTypes: [1] },
    "unbreakable": { category: "community", description: "霸体", fileTypes: [11] },
    "counter": { category: "community", description: "破招", fileTypes: [11] },
    "event super on scr": { category: "community", description: "怪物在一定条件下触发霸体", fileTypes: [11] },
    "attack enemy": { category: "community", description: "敌伤判定（禁用时不会造成伤害）", fileTypes: [9] },
    "haste": { category: "community", description: "增益效果", fileTypes: [9] },
    "burn": { category: "community", description: "异常效果", fileTypes: [2] },
    "bless": { category: "community", description: "增益效果", fileTypes: [9] },
    "atk super on scr": { category: "community", description: "使用指定攻击动作时进入霸体", fileTypes: [11] },
    "down motion": { category: "community", description: "倒地动作", fileTypes: [11] },
    "damage motion 1": { category: "community", description: "受击动作", fileTypes: [11] },
    "move motion": { category: "community", description: "移动动作", fileTypes: [11] },
    "waiting motion": { category: "community", description: "静止动作", fileTypes: [11] },
    "stuckbonus on damage": { category: "community", description: "两个数值为1组", fileTypes: [11] },
    "superarmor on attack": { category: "community", description: "发起攻击时进入霸体", fileTypes: [11] },
    "deelement resistance": { category: "community", description: "元素属性剥离抗性", fileTypes: [3] },
    "deadlystrike resistance": { category: "community", description: "致命一击抗性", fileTypes: [3] },
    "deadlystrike": { category: "community", description: "异常效果", fileTypes: [3] },
    "armor break": { category: "community", description: "异常效果", fileTypes: [9] },
    "weapon break": { category: "community", description: "异常效果", fileTypes: [9] },
    "weakness": { category: "community", description: "异常效果", fileTypes: [9] },
    "piercing": { category: "community", description: "异常效果", fileTypes: [9] },
    "deelement": { category: "community", description: "异常效果", fileTypes: [9] },
    "stat change": { category: "community", description: "使用消耗品时硬直度增加1000", fileTypes: [3] },
    "active status": { category: "community", description: "此攻击附带的异常/增益状态", fileTypes: [9] },
    "die effect": { category: "community", description: "怪物被击杀时的特效", fileTypes: [11] },
    "sit motion": { category: "community", description: "倒地起身动画", fileTypes: [11] },
    "destination change term": { category: "community", description: "存在多个敌对目标时", fileTypes: [21] },
    "think term": { category: "community", description: "思考时间（1000 = 1秒）", fileTypes: [21] },
    "targeting nearest": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting time term": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting on attack": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting on damage": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting high level": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting low level": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting high hp": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting low hp": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting attacker": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting from direction": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting low physical attack": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting low physical defense": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting low magical attack": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting low magical defense": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "targeting downed": { category: "community", description: "怪物AI逻辑", fileTypes: [11] },
    "hit recovery": { category: "community", description: "硬直（数值越高", fileTypes: [11] },
    "attack kind": { category: "community", description: "怪物的攻击类型", fileTypes: [11] },
    "face image": { category: "community", description: "怪物在血条位置的头像", fileTypes: [11] },
    "damage motion 2": { category: "community", description: "处于地面的受击动作", fileTypes: [11] },
    "overturn motion": { category: "community", description: "受到浮空效果的动作", fileTypes: [11] },
    "attack motion": { category: "community", description: "攻击动作", fileTypes: [11] },
    "weapon damage apply": { category: "community", description: "开启改1 关闭改0", fileTypes: [9] },
    "elemental property": { category: "community", description: "为该攻击或装备赋予属性", fileTypes: [9] },
    "attack friend": { category: "community", description: "友伤判定（开启时可以对友方造成伤害）", fileTypes: [9] },
    "damage reaction": { category: "community", description: "伤害判定", fileTypes: [9] },
    "hit wav": { category: "community", description: "命中音效", fileTypes: [9] },
    "knuck back": { category: "community", description: "击退", fileTypes: [9] },
    "attack direction": { category: "community", description: "攻击方向", fileTypes: [9] },
    "hit down": { category: "community", description: "攻击判定", fileTypes: [9] },
    "hit horizon": { category: "community", description: "攻击判定", fileTypes: [9] },
    "hit lift up": { category: "community", description: "攻击判定", fileTypes: [9] },
    "no blood": { category: "community", description: "打击类型", fileTypes: [9] },
    "blood": { category: "community", description: "打击类型", fileTypes: [9] },
    "hit info": { category: "community", description: "打击类型", fileTypes: [9] },
    "attack info": { category: "community", description: "攻击信息", fileTypes: [11] },
    "common champion elemental property": { category: "community", description: "普通精英怪的属性", fileTypes: [11] },
    "speech on situation": { category: "community", description: "台词信息", fileTypes: [11] },
    "human armor": { category: "community", description: "人形护甲", fileTypes: [11] },
    "divine armor": { category: "community", description: "神圣护甲", fileTypes: [11] },
    "category": { category: "community", description: "怪物类型", fileTypes: [11] },
    "common champion drop item": { category: "community", description: "普通精英怪的[独立掉落]", fileTypes: [11] },
    "usable job": { category: "community", description: "在道具里为可以使用的职业", fileTypes: [3] },
    "compound emblem": { category: "community", description: "徽章合成", fileTypes: [24] },
    "convert avatar": { category: "community", description: "重铸徽章", fileTypes: [24] },
    "create guild agit": { category: "community", description: "创建公会", fileTypes: [24] },
    "delete guild agit": { category: "community", description: "解散公会", fileTypes: [24] },
    "guild": { category: "community", description: "公会", fileTypes: [24] },
    "item shop": { category: "community", description: "NPC商店", fileTypes: [24] },
    "job change": { category: "community", description: "副职业", fileTypes: [24] },
    "product item": { category: "community", description: "生产", fileTypes: [24] },
    "recover stamina": { category: "community", description: "解除虚弱", fileTypes: [24] },
    "secret shop": { category: "community", description: "加百利商店", fileTypes: [24] },
    "sera shop": { category: "community", description: "进入商城", fileTypes: [24] },
    "time sand": { category: "community", description: "导师技能商店（或许是）", fileTypes: [24] },
    "upgrade item": { category: "community", description: "强化装备", fileTypes: [24] },
    "at swordman": { category: "community", description: "女鬼剑士", fileTypes: [41] },
    "minimum info": { category: "community", description: "APC的基础信息", fileTypes: [21] },
    "skill command advantage": { category: "community", description: "左边若为20将减少最大冷却时间2%\t 右边若为50将减少魔法值消耗5%", fileTypes: [15] },
    "image": { category: "community", description: "在此标签下添加npk路径以调用npk文件的贴图，贴图npk文件的位置在客户端的[ImagePacks2]文件夹", fileTypes: [1] },
    "sound": { category: "community", description: "环境音乐位置在客户端的[SoundPacks]（大概是）", fileTypes: [10] }
};
