// ============================================================
//  PVF 标签解析定义表 (通用文件)
//  用于 [xxx] 标签的浮窗解析说明：字段描述、参数解析等
//
//  扩展方式：
//    1. 在 PVF_TAGS 中新增条目，key 为标签名（不含方括号，小写）
//    2. 每个条目字段：
//       - description: 标签用途描述
//       - params:      参数列表 [{ name, type, desc, required }]
//       - example:     使用示例
//       - category:    分类（用于按类展示）
//       - remark:      补充说明（可选）
//    3. 不在此表中的标签会回落到 PVF_TAG_FALLBACK（默认提示）
// ============================================================

// 标签分类说明（便于后续按类筛选/着色）
export const PVF_TAG_CATEGORIES = {
    appearance: "外观 / 资源引用",
    attribute: "基础属性",
    battle: "战斗 / 伤害",
    skill: "技能 / 状态",
    item: "道具 / 物品",
    control: "流程 / 条件控制",
    system: "系统 / 元信息",
    other: "其它"
};

// ============================================================
//  PVF 块标签集（必须闭合的标签）
//  这些标签必须成对出现：[tag] ... [/tag]
//  数据来源：对 Script.pvf 全量解压统计，闭合/开启比 ≥ 0.9 的标签。
//  不在此集合中的标签视为「独立标签」，可不使用 [/tag] 闭合。
//  后续扩展：直接向数组中追加标签名（小写）。
// ============================================================
export const PVF_BLOCK_TAGS = new Set([
    "1st favor dialog",
    "3choro enchant",
    "a condition item",
    "ability case",
    "ability category",
    "absolute bind cube",
    "absolute bind plus rare",
    "absolute start path",
    "account collision quest",
    "action",
    "action assign",
    "action list",
    "action type",
    "action usable dungeon",
    "action usable place",
    "action usable server type",
    "active status buff",
    "add appendage",
    "add level info",
    "add object effect",
    "add particles",
    "add rate",
    "add skill summon",
    "add socket limited avatar",
    "add static data",
    "additional character status",
    "adjust hp gauge",
    "advance altar clear reward",
    "advance altar map",
    "advance altar survival clear reward",
    "advance altar survival map",
    "ai pattern",
    "all skill item",
    "ambient",
    "amplification random value",
    "ani info",
    "animation",
    "answer list",
    "any body equipped",
    "apc",
    "apc create condition",
    "apc list",
    "apid string",
    "appendage stackable buff index",
    "apply date",
    "apply dungeon type",
    "apply type",
    "area index",
    "area list",
    "artifact slot",
    "assault",
    "atk super on scr",
    "attack action",
    "attack down prob",
    "attack kind",
    "attack motion",
    "attacked monster info",
    "attraction force appendage",
    "aura ability",
    "aura pos datas",
    "autoskill",
    "avatar",
    "avatar booster preview",
    "avatar emblem target type",
    "avatar index set",
    "avatar list",
    "avatar select ability",
    "avatar type select",
    "awakening quest reward",
    "awakening skill",
    "awakening skill index",
    "background animation",
    "background effect",
    "balloon message",
    "base result",
    "bead item",
    "bead limited usable item",
    "before rendering info",
    "behavior",
    "belt avatar",
    "belt scroll map",
    "block effect",
    "block use stackable item",
    "blood monster",
    "blood phase time",
    "bonus item",
    "booster appendage",
    "booster category autoget from job",
    "booster category name",
    "booster info",
    "booster level",
    "booster select category",
    "boosting ani",
    "boss item drop list",
    "boss map",
    "buff info",
    "buff list",
    "button action",
    "call the name",
    "camera edge exception",
    "camera edge recovery object",
    "camera force move",
    "can beat index",
    "can not give item",
    "caracter cutscene",
    "cargo transport stone enable equip type",
    "cargo transport stone except etc",
    "cargo transport stone except index",
    "cargo transport stone grade",
    "cargo transport stone include index",
    "cargo transport stone rarity weight",
    "case",
    "cash item",
    "catch item",
    "category",
    "category entry",
    "category event tag",
    "center index",
    "cera",
    "change",
    "change action by condition",
    "change depend on grow job",
    "change map",
    "change status buff",
    "change ultimatecutscene ani file",
    "changeable button",
    "channel",
    "channel name",
    "character item check",
    "character job",
    "character level up",
    "character status rate",
    "character status rate special",
    "characteristic",
    "charactor",
    "charm upgrade table",
    "check",
    "check count",
    "check event type",
    "check player num",
    "check raid dungeon is index",
    "checkup",
    "chn random image percent",
    "choice count",
    "choose part",
    "chronicle grow type",
    "class change quest reward",
    "clear condition",
    "clear reward item",
    "coat avatar",
    "coin info",
    "collision info",
    "collision quest",
    "color change effect",
    "colosseum disjoint info",
    "combo",
    "combo set",
    "commands",
    "common champion drop item",
    "common champion elemental property",
    "common champion item drop list",
    "common monster item drop list",
    "common passive object",
    "compare",
    "competition area",
    "condition data",
    "conditional summon monster",
    "connect quest unit",
    "contents",
    "control panel",
    "control passive object",
    "convert info",
    "convert type",
    "counter attack",
    "counter revision table",
    "coupleroom item",
    "create equipment list",
    "create passiveobject",
    "creature",
    "creature costume",
    "creature special feature",
    "cube index",
    "custom animation",
    "custom skill level",
    "custom wav",
    "customized screen edge",
    "daily item",
    "dash attack",
    "data",
    "data entry",
    "day attacked monster info",
    "day specific attacked monster info",
    "death tower",
    "death tower item",
    "decorate enchant",
    "default ani",
    "default equipment index",
    "default promotion page",
    "delete appendage",
    "depend give item",
    "destroy data",
    "destroy method",
    "dialog",
    "dialog depend on job",
    "dialog list",
    "dialog on map complete",
    "dialog on map start",
    "dim",
    "disguise appendage",
    "doll special dungeon",
    "dont change grow type",
    "draw new position balloon",
    "drop avatar item",
    "dungeon",
    "dungeon check",
    "dungeon exp bonus monster",
    "dungeon info",
    "dungeon loading message",
    "dungeon minimap icon setting",
    "dungeon party balance",
    "dye info",
    "dying",
    "easy",
    "eat feed",
    "effect equipment part set",
    "effect file levels",
    "emancipate",
    "emblem",
    "emblem socket default",
    "emergency state recovery",
    "enchant",
    "enchant index",
    "enchant random",
    "enchant table",
    "end addtional animation",
    "end buff",
    "enemies alive",
    "enemy center index",
    "enemy reward item",
    "epic_index",
    "episode",
    "equip",
    "equipment",
    "equipment definition",
    "equipment index",
    "equipment item",
    "equipment list",
    "equipment part set",
    "equipment reinforce type",
    "equipment upgrade",
    "er_enchant",
    "etc",
    "etc action",
    "etc attack info",
    "etc motion",
    "event gift item",
    "event info",
    "event monster",
    "event monster position",
    "event monster2",
    "event monster3",
    "event reward item",
    "event rhythm action",
    "event super on scr",
    "event time",
    "event use skill",
    "event_favor_dialog",
    "evolution",
    "example",
    "exception quest",
    "exceptional character",
    "exceptions",
    "exclusive dungeon",
    "executable skills",
    "executable states",
    "exp base",
    "expand ani",
    "expertjob only",
    "extended tile",
    "extra condition",
    "face avatar",
    "fail output",
    "fail title item",
    "favor",
    "favor level reward mail",
    "favor_dialog",
    "favor_dialog_exception",
    "favor_duration_reward_buff",
    "favor_duration_reward_buff_dialog",
    "favorable relationship",
    "field role",
    "file path",
    "fill point under",
    "final title item id",
    "finish system success effects",
    "first int data",
    "fixed level skill",
    "flash",
    "flash screen",
    "float",
    "float data",
    "gate enable",
    "generation time",
    "get eventitem fatigue",
    "get exp",
    "get out",
    "ghost motion",
    "gift disallowance",
    "gift item",
    "give group",
    "goguide",
    "grab off",
    "grab on",
    "graphic effect change",
    "grid index",
    "grid map",
    "group",
    "group type",
    "grow type effect",
    "guard appendage",
    "guest gift",
    "guide exception",
    "guild agit entrance info",
    "hair avatar",
    "hard",
    "hardcoding parameter",
    "hat avatar",
    "hell freepass item",
    "hell info",
    "hell quest",
    "hide equipment",
    "hide grow avatar",
    "hide growtype avatar",
    "hide layer",
    "hide skill",
    "hits over",
    "hits under",
    "hold attack",
    "homing",
    "hotnew sell ipg",
    "hp appendage",
    "hp invincible pattern",
    "if",
    "image list",
    "image packs",
    "immediately adaptive product",
    "immune active status",
    "immune inactive status",
    "immune start action",
    "impossible contents",
    "impossible equip module",
    "impossible jobs",
    "impossible skills",
    "in alfhlyra",
    "in elven gard",
    "in stom pass",
    "increase status type",
    "index list",
    "indexes",
    "info",
    "ingredient",
    "init cooltime",
    "initial target",
    "input item",
    "int",
    "int data",
    "integer",
    "interpolation move target",
    "invalid ani",
    "invalid custom anis",
    "invalid frames",
    "is in area",
    "is in gate",
    "is in point area",
    "is index",
    "is not index",
    "is not targetactivestatus",
    "is object type",
    "is target states or",
    "is team",
    "is term unit minute",
    "item category",
    "item condition",
    "item drop rarity control",
    "item event",
    "item info",
    "item list",
    "item second",
    "items",
    "itemshop category",
    "job const",
    "job info",
    "job name",
    "jump attack",
    "jump to target ex",
    "key cooltime",
    "key item",
    "key stream",
    "key value index",
    "key value string",
    "kinggoldenhorn kingsilverhorn allow level",
    "kinggoldenhorn kingsilverhorn condition",
    "legacy info",
    "level info",
    "level info multiply",
    "level linear ability",
    "level of difficulty",
    "level property",
    "level section ability",
    "level section ani",
    "level up",
    "level up reward",
    "levelup section rewards",
    "limit count",
    "limit dungeon",
    "limit dungeon index",
    "limit passiveobject",
    "limit slowdown",
    "limit upgradable level",
    "linked dungeon",
    "list",
    "loading cutscene info",
    "loop addtional animation",
    "mail enclose",
    "main game",
    "map over move ani",
    "map specification",
    "matching info",
    "material_master",
    "material_upper",
    "max grow count",
    "medium",
    "mesmerization damage balance",
    "minimap process bar",
    "mission",
    "module",
    "monster card id",
    "monster condition",
    "monster difficulty bonus",
    "monster index",
    "monster reward item",
    "monster specific ai",
    "monster type spawn prob",
    "mood",
    "motion",
    "move dir",
    "move layered map",
    "move list",
    "move map",
    "move pattern",
    "move to destination",
    "movement check",
    "movie play",
    "movie unit",
    "multiple then",
    "must clear quest index",
    "name tag bar offset",
    "name tag img",
    "name tag offset",
    "named monster",
    "neck avatar",
    "need material",
    "need quest",
    "need skill",
    "next",
    "none feed",
    "not equipped index",
    "not stackable buy",
    "npc list",
    "npc visibility",
    "nutappendageinfo",
    "object",
    "object destroy condition",
    "one a day item",
    "open broadcasting info",
    "open window",
    "option",
    "option group",
    "output",
    "output item",
    "over skill gauge full",
    "over skill level values",
    "over skill waiting",
    "overlapping check",
    "package",
    "package data",
    "package data include usable period",
    "package data selection",
    "package selection",
    "pants avatar",
    "param",
    "part set info",
    "party count for hp max rate",
    "party member",
    "party member coin limit table",
    "party target",
    "passive object",
    "passive object in stackable",
    "passive object index",
    "pathgate info",
    "patrol route",
    "penalty",
    "permission",
    "phase",
    "physical attack besed on diff",
    "piece set ability",
    "piercing",
    "play info",
    "pop random",
    "popupwindow design",
    "postal",
    "pre required quest",
    "pre required skill",
    "precedence skill",
    "prefer item",
    "prefer item group",
    "preload appendage",
    "premium",
    "premium service",
    "press creature button",
    "prev",
    "priority group",
    "process time seconds",
    "pull appendage",
    "purchase cost",
    "purchase gold",
    "purchase gsp",
    "puzzle info",
    "pvp",
    "pvp channel limit npc",
    "pvp grade",
    "pvp map basic data",
    "quest animation",
    "quest condition",
    "quest index",
    "quest list",
    "quest status",
    "question data",
    "question info",
    "quick item",
    "quick skill",
    "quick skill expend",
    "ramdom animation",
    "random generate passive object",
    "random motion",
    "random probability",
    "random reward item",
    "random select",
    "randombox",
    "randomized object creation",
    "rank over",
    "rank type",
    "rank under",
    "rare rate",
    "rarity possible explain",
    "reached decision level",
    "ready action",
    "recipe custom upgrade table",
    "recommend equipment",
    "recommend party",
    "recommended avatar list",
    "reflection object",
    "region name",
    "regist condition",
    "reinforcement usable item list",
    "release ani",
    "renamed",
    "replace avatar ani",
    "required item",
    "required job skill",
    "resource title item",
    "resource title item id",
    "result info",
    "result item",
    "reward data",
    "reward group",
    "reward int data",
    "reward selection int data",
    "reward table",
    "reward victory emblem",
    "reward_server",
    "rhythm action",
    "ridableskill definition",
    "ridableskill explanation",
    "role",
    "room list",
    "round",
    "routing priority",
    "rp",
    "scene info",
    "schedule",
    "schedule buff",
    "scheduled flavor text",
    "scroll animation",
    "sealing removal item",
    "second awakening quest reward",
    "second awakening skill index",
    "section",
    "select group",
    "selection list",
    "selective grow creature",
    "sell info",
    "send",
    "send mail",
    "sequence",
    "server",
    "set ability",
    "set hp percent damage",
    "set item",
    "set minimum active status resistance",
    "set minimum tolerance and defence",
    "set movevels",
    "set pos force",
    "set speed",
    "shake",
    "shield",
    "shoes avatar",
    "shop",
    "show hitgauge",
    "show npc dialog",
    "show_dialog",
    "skill",
    "skill apply condition",
    "skill cooltime set item rate",
    "skill correction",
    "skill data up",
    "skill fitness growtype",
    "skill fitness second growtype",
    "skill gauge full",
    "skill level values",
    "skill levelup",
    "skill list",
    "skill node",
    "skill preloading image",
    "skill string",
    "skill under cooltime effect",
    "skill under cooltime effect each",
    "skill_instance",
    "skilllist",
    "slot",
    "slotmachine unit",
    "slots",
    "sniper type",
    "socket info",
    "sound",
    "sound category",
    "sound probability",
    "spawn boss index",
    "spawn common champion index",
    "spawn common monster index",
    "spawn step resource pool",
    "spawn super champion index",
    "spec",
    "special avatar",
    "special level up",
    "special passive object",
    "special passive object item",
    "special purchase cost",
    "special quest",
    "special reward status",
    "specific attacked monster info",
    "specific product mileage",
    "specified remain skill cooltime change",
    "speech",
    "speech on",
    "speech on situation",
    "speech pos",
    "speed control passive objects",
    "stackable",
    "stackable action limit index",
    "stackable action limit indexes",
    "stackable action pair indexes",
    "stackable action result limit indexes",
    "stackable appendage",
    "stackable item",
    "start addtional animation",
    "start map",
    "state special",
    "static and level data path",
    "static basic skill",
    "static data",
    "static data multiply",
    "static player start pos",
    "step info",
    "stone type",
    "str data",
    "straight move",
    "string",
    "string data",
    "sub",
    "sub ani",
    "sub ani with xyz",
    "substitutive names",
    "success title item",
    "suitable job",
    "summon",
    "summon line",
    "summon monster",
    "summon monster status rate",
    "super champion drop item",
    "super champion item drop list",
    "switch",
    "tab",
    "table",
    "table grow type",
    "target character",
    "target dungeon index",
    "target item id",
    "team status rate",
    "teleport",
    "teleport trap",
    "text info",
    "then",
    "think",
    "throw attack",
    "tile",
    "tile files",
    "tile map",
    "tile option",
    "time line",
    "title change item id",
    "title collection info",
    "tower recovery",
    "tower stage",
    "town index",
    "town loading message",
    "town movable area",
    "towns",
    "transparency",
    "tree",
    "ui index",
    "uniq item info",
    "unit",
    "unprefer item",
    "unprefer item group",
    "upgrade exclusive material",
    "upgrade limit cube info",
    "upgrade linear ability",
    "upgrade weapon attack power rate",
    "upper rare rate",
    "usable creature index",
    "usable creature str",
    "usable dungeon",
    "usable equip type",
    "usable job",
    "usable passiveobject",
    "usable world",
    "use fatigue only start dungeon",
    "use skill",
    "user",
    "using overskill",
    "using skill",
    "variable stat",
    "victory motion",
    "virtual movable area",
    "warning",
    "warp attack",
    "warp map condition",
    "warroom",
    "weapon hit info",
    "weapon overspec per item",
    "weapon skill info",
    "weapon wav",
    "world",
    "world drop",
    "world object",
    "坷宏璃飘"
]);

// 判断标签是否为「必须闭合的块标签」
export function isBlockTag(tagName) {
    if (!tagName) return false;
    return PVF_BLOCK_TAGS.has(parseTagName(tagName).toLowerCase());
}

// 标签定义表 —— 后续在此扩展
export const PVF_TAGS = {
    // ---- 外观 / 资源引用 ----
    avatar: {
        category: "appearance",
        description: "角色头像 / 立绘资源引用",
        params: [{ name: "sprite", type: "string", desc: "img 资源路径或索引", required: true }],
        example: "[avatar]`character/001.img`",
        remark: "通常在 .lst 列表中与 ID 配对出现"
    },
    illustration: {
        category: "appearance",
        description: "插画资源引用",
        params: [{ name: "sprite", type: "string", desc: "插画资源路径", required: true }],
        example: "[illustration]`ui/illust/01.img`"
    },
    sound: {
        category: "appearance",
        description: "音效资源引用",
        params: [{ name: "path", type: "string", desc: "sound 资源路径", required: true }],
        example: "[sound]`sound/effect/attack.wav`"
    },

    // ---- 基础属性 ----
    level: {
        category: "attribute",
        description: "等级数值",
        params: [{ name: "value", type: "int", desc: "等级（≥1）", required: true }],
        example: "[level] 10"
    },
    hp: {
        category: "attribute",
        description: "生命值上限",
        params: [{ name: "value", type: "int", desc: "HP 数值", required: true }],
        example: "[hp] 9999"
    },
    mp: {
        category: "attribute",
        description: "魔法值上限",
        params: [{ name: "value", type: "int", desc: "MP 数值", required: true }],
        example: "[mp] 500"
    },
    strength: {
        category: "attribute",
        description: "力量属性",
        params: [{ name: "value", type: "int", desc: "力量数值", required: true }],
        example: "[strength] 100"
    },
    intelligence: {
        category: "attribute",
        description: "智力属性",
        params: [{ name: "value", type: "int", desc: "智力数值", required: true }],
        example: "[intelligence] 100"
    },

    // ---- 战斗 / 伤害 ----
    "physical attack": {
        category: "battle",
        description: "物理攻击力",
        params: [{ name: "value", type: "int|float", desc: "物攻数值", required: true }],
        example: "[physical attack] 1200"
    },
    "magical attack": {
        category: "battle",
        description: "魔法攻击力",
        params: [{ name: "value", type: "int|float", desc: "魔攻数值", required: true }],
        example: "[magical attack] 980"
    },
    "physical defense": {
        category: "battle",
        description: "物理防御力",
        params: [{ name: "value", type: "int|float", desc: "物防数值", required: true }],
        example: "[physical defense] 600"
    },
    "magical defense": {
        category: "battle",
        description: "魔法防御力",
        params: [{ name: "value", type: "int|float", desc: "魔防数值", required: true }],
        example: "[magical defense] 600"
    },
    cooldown: {
        category: "battle",
        description: "冷却时间（毫秒）",
        params: [{ name: "ms", type: "int", desc: "冷却毫秒数", required: true }],
        example: "[cooldown] 5000"
    },
    duration: {
        category: "battle",
        description: "持续时间（秒）",
        params: [{ name: "sec", type: "int|float", desc: "持续秒数", required: true }],
        example: "[duration] 3.5"
    },
    probability: {
        category: "battle",
        description: "触发概率（百分比）",
        params: [{ name: "percent", type: "float", desc: "0~100 之间的概率值", required: true }],
        example: "[probability] 25.0"
    },

    // ---- 技能 / 状态 ----
    skill: {
        category: "skill",
        description: "技能标识",
        params: [{ name: "id", type: "int|string", desc: "技能 ID 或名称", required: true }],
        example: "[skill] 15001"
    },
    state: {
        category: "skill",
        description: "状态效果标识",
        params: [{ name: "id", type: "int|string", desc: "状态 ID 或名称", required: true }],
        example: "[state] `poison`"
    },
    buff: {
        category: "skill",
        description: "增益效果",
        params: [
            { name: "type", type: "string", desc: "buff 类型", required: true },
            { name: "value", type: "int", desc: "数值" }
        ],
        example: "[buff] `atk_up` 200"
    },

    // ---- 道具 / 物品 ----
    item: {
        category: "item",
        description: "道具引用",
        params: [{ name: "id", type: "int", desc: "道具 ID", required: true }],
        example: "[item] 100032"
    },
    stack: {
        category: "item",
        description: "堆叠数量",
        params: [{ name: "count", type: "int", desc: "堆叠上限", required: true }],
        example: "[stack] 99"
    },
    price: {
        category: "item",
        description: "售价（金币）",
        params: [{ name: "value", type: "int", desc: "金币数量", required: true }],
        example: "[price] 5000"
    },

    // ---- 流程 / 条件控制 ----
    condition: {
        category: "control",
        description: "条件判断块",
        params: [{ name: "expr", type: "string", desc: "条件表达式", required: true }],
        example: "[condition] `level >= 10`"
    },
    if: {
        category: "control",
        description: "如果分支",
        params: [{ name: "expr", type: "string", desc: "条件表达式", required: true }],
        example: "[if] `hp > 0`"
    },
    else: {
        category: "control",
        description: "否则分支",
        params: [],
        example: "[else]"
    },

    // ---- 系统 / 元信息 ----
    version: {
        category: "system",
        description: "版本号",
        params: [{ name: "ver", type: "int|string", desc: "版本", required: true }],
        example: "[version] 1003"
    },
    name: {
        category: "system",
        description: "名称字符串引用",
        params: [{ name: "key", type: "string", desc: "字符串表 key", required: true }],
        example: "[name] `str/class/fighter`"
    },
    comment: {
        category: "system",
        description: "注释说明（仅文本用途）",
        params: [{ name: "text", type: "string", desc: "注释内容", required: true }],
        example: "[comment] `此处为暴击分支`"
    }
};

// 未知标签的默认回落说明
export const PVF_TAG_FALLBACK = {
    description: "未收录的标签，请在 pvfTags.js 中补充定义",
    params: [],
    category: "other"
};

// ---- 解析 [xxx] 标签名（去除方括号、闭合斜杠与首尾空白）----
export function parseTagName(token) {
    if (!token) return "";
    let t = String(token).trim();
    if (t.startsWith("[")) t = t.slice(1);
    if (t.endsWith("]")) t = t.slice(0, -1);
    // 闭合标签 [/xxx] -> xxx，便于浮窗/块标签判断复用同一份定义
    if (t.startsWith("/")) t = t.slice(1);
    return t.trim();
}

// ---- 获取标签说明信息（大小写不敏感，支持带/不带方括号）----
export function getTagInfo(tagName) {
    if (!tagName) return null;
    const name = parseTagName(tagName).toLowerCase();
    if (!name) return null;
    const block = PVF_BLOCK_TAGS.has(name);
    if (PVF_TAGS[name]) {
        return { name, block, ...PVF_TAGS[name] };
    }
    // 子串模糊匹配（便于检索复合标签）
    for (const key of Object.keys(PVF_TAGS)) {
        if (key.includes(name) || name.includes(key)) {
            return { name: key, block: PVF_BLOCK_TAGS.has(key), ...PVF_TAGS[key] };
        }
    }
    return { name, block, ...PVF_TAG_FALLBACK };
}

// ---- 渲染标签的浮窗 HTML（用于自定义 tooltip）----
export function renderTagTooltip(tagName) {
    const info = getTagInfo(tagName);
    if (!info) return "";
    const lines = [];
    const categoryLabel = PVF_TAG_CATEGORIES[info.category] || info.category || "";
    lines.push(`<div class="pvf-tip-name">[${info.name}]</div>`);
    if (categoryLabel) lines.push(`<div class="pvf-tip-cat">${categoryLabel}</div>`);
    if (info.block) lines.push(`<div class="pvf-tip-block">块标签 · 必须以 [/${info.name}] 闭合</div>`);
    lines.push(`<div class="pvf-tip-desc">${escapeHtml(info.description || "")}</div>`);
    if (Array.isArray(info.params) && info.params.length > 0) {
        lines.push(`<div class="pvf-tip-section">参数</div>`);
        for (const p of info.params) {
            const req = p.required ? '<span class="pvf-tip-req">必填</span>' : '<span class="pvf-tip-opt">可选</span>';
            lines.push(
                `<div class="pvf-tip-param">` +
                    `<span class="pvf-tip-pname">${escapeHtml(p.name || "")}</span>` +
                    `<span class="pvf-tip-ptype">${escapeHtml(p.type || "")}</span>` +
                    req +
                    `<span class="pvf-tip-pdesc">${escapeHtml(p.desc || "")}</span>` +
                    `</div>`
            );
        }
    }
    if (info.example) {
        lines.push(`<div class="pvf-tip-section">示例</div>`);
        lines.push(`<code class="pvf-tip-example">${escapeHtml(info.example)}</code>`);
    }
    if (info.remark) {
        lines.push(`<div class="pvf-tip-remark">${escapeHtml(info.remark)}</div>`);
    }
    return lines.join("");
}

function escapeHtml(s) {
    return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
